[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18.20.3"

[[plugins]]
  package = "@netlify/plugin-nextjs"
